import React, { useEffect, useState } from 'react'
import api from '../services/api'
import LoadingState from '../components/LoadingState'
import GmailConnectCard from '../components/GmailConnectCard'
import { useAuth } from '../context/AuthContext'

export default function ApplicationSupport() {
  const { user } = useAuth()
  const [applications, setApplications] = useState([])
  const [opportunities, setOpportunities] = useState({})
  const [loading, setLoading] = useState(true)
  const [copiedId, setCopiedId] = useState(null)
  const [sendingId, setSendingId] = useState(null)
  const [sendError, setSendError] = useState({})

  async function load() {
    setLoading(true)
    try {
      const [aRes, oRes] = await Promise.all([
        api.get('/applications'),
        api.get('/opportunities'),
      ])
      setApplications(aRes.data)
      const map = {}
      oRes.data.forEach((o) => { map[o.id] = o })
      setOpportunities(map)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { load() }, [])

  function copy(text, id) {
    navigator.clipboard?.writeText(text)
    setCopiedId(id)
    setTimeout(() => setCopiedId(null), 1500)
  }

  async function handleSend(applicationId) {
    setSendingId(applicationId)
    setSendError((e) => ({ ...e, [applicationId]: '' }))
    try {
      await api.post(`/applications/${applicationId}/send`)
      await load()
    } catch (err) {
      setSendError((e) => ({ ...e, [applicationId]: err.response?.data?.detail || 'Failed to send' }))
    } finally {
      setSendingId(null)
    }
  }

  if (loading) return <LoadingState />

  return (
    <div className="max-w-3xl mx-auto px-4 py-8">
      <h1 className="text-2xl font-bold text-slate-900 mb-1">Application Support</h1>
      <p className="text-slate-500 mb-6">
        Personalized cover letters generated by the Application Agent for your shortlisted matches.
      </p>

      <GmailConnectCard />

      {applications.length === 0 ? (
        <p className="text-slate-500">No application packages generated yet. Generate one from the Matches page.</p>
      ) : (
        <div className="space-y-6">
          {applications.map((a) => {
            const opp = opportunities[a.opportunity_id]
            return (
              <div key={a.id} className="card">
                <div className="flex items-center justify-between mb-3">
                  <div>
                    <h3 className="font-semibold text-slate-900">{opp?.title || 'Opportunity'}</h3>
                    <p className="text-sm text-slate-500">{opp?.organization}</p>
                  </div>
                  {a.sent ? (
                    <span className="badge bg-emerald-50 text-emerald-700">✅ Sent to {a.sent_to}</span>
                  ) : (
                    <button className="btn-secondary" onClick={() => copy(a.cover_letter, a.id)}>
                      {copiedId === a.id ? 'Copied ✓' : 'Copy'}
                    </button>
                  )}
                </div>

                <pre className="whitespace-pre-wrap text-sm text-slate-700 font-sans bg-slate-50 rounded-lg p-4">
                  {a.cover_letter}
                </pre>

                {a.highlights?.length > 0 && (
                  <div className="mt-3 flex flex-wrap gap-1.5">
                    {a.highlights.map((h) => <span key={h} className="badge bg-brand-50 text-brand-700">{h}</span>)}
                  </div>
                )}

                {!a.sent && (
                  <div className="mt-4 pt-4 border-t border-slate-100">
                    <button
                      className="btn-primary w-full"
                      disabled={sendingId === a.id}
                      onClick={() => handleSend(a.id)}
                    >
                      {sendingId === a.id
                        ? 'Sending…'
                        : user?.gmail_connected
                          ? `✉️ Send Application${opp?.organization ? ` to ${opp.organization}` : ''}`
                          : '✉️ Connect Gmail above to Send'}
                    </button>
                    {sendError[a.id] && <p className="text-sm text-red-600 mt-2">{sendError[a.id]}</p>}
                  </div>
                )}
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}
